version: '3.5'

x-defaults: &defaults
  restart: always
  logging:
    driver: json-file
    options:
      max-size: "50m"
      max-file: "5"
  env_file:
    - .env

services:
  radius-server:
    <<: *defaults
    build: radius
    container_name: radius-server
    network_mode: host
  radius-api:
    <<: *defaults
    build: api
    container_name: radius-api
    network_mode: host
